// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TumisugiApp.Data;

#nullable disable

namespace TumisugiApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129151210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreDetail", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreMajorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("GenreMajorCode");

                    b.ToTable("GetGenreDetails");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            GenreMajorCode = 1,
                            Name = "RPG",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 2,
                            GenreMajorCode = 1,
                            Name = "アクション",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 3,
                            GenreMajorCode = 1,
                            Name = "アドベンチャー",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 4,
                            GenreMajorCode = 1,
                            Name = "ストラテジ",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 5,
                            GenreMajorCode = 1,
                            Name = "レース",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 6,
                            GenreMajorCode = 1,
                            Name = "音ゲー",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 7,
                            GenreMajorCode = 1,
                            Name = "STG",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 8,
                            GenreMajorCode = 1,
                            Name = "カード",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 9,
                            GenreMajorCode = 1,
                            Name = "ギャルゲ",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 99,
                            GenreMajorCode = 1,
                            Name = "その他",
                            UpdateAt = "2026-01-28 00:00:00"
                        });
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreMajor", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("GetGenreMajors");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Name = "Game",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 2,
                            Name = "Anime",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 3,
                            Name = "Book",
                            UpdateAt = "2026-01-28 00:00:00"
                        });
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.Platform", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Name = "PC",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 2,
                            Name = "PlayStation",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 3,
                            Name = "Switch",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 4,
                            Name = "Mobile",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 5,
                            Name = "Web",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 6,
                            Name = "others",
                            UpdateAt = "2026-01-28 00:00:00"
                        });
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.Status", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Name = "未購入",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 2,
                            Name = "未プレイ",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 3,
                            Name = "放置中",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 4,
                            Name = "プレイ中",
                            UpdateAt = "2026-01-28 00:00:00"
                        },
                        new
                        {
                            Code = 5,
                            Name = "積み解消",
                            UpdateAt = "2026-01-28 00:00:00"
                        });
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TumiManageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode");

                    b.HasIndex("TumiManageId");

                    b.ToTable("TumiHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusCode = 3,
                            TumiManageId = 1,
                            UpdateAt = "2026-01-28 00:00:00"
                        });
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreDetailCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreMajorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreDetailCode");

                    b.HasIndex("GenreMajorCode");

                    b.HasIndex("PlatformCode");

                    b.HasIndex("StatusCode");

                    b.ToTable("TumiManagements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreDetailCode = 1,
                            GenreMajorCode = 1,
                            Memo = "セイバールートのみクリアしているが他ルートもやりたい...",
                            Name = "Fate/StayNight",
                            PlatformCode = 1,
                            StatusCode = 3,
                            UpdateAt = "2026-01-28 00:00:00"
                        });
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreDetail", b =>
                {
                    b.HasOne("TumisugiApp.Models.Entities.GenreMajor", "GenreMajor")
                        .WithMany("Details")
                        .HasForeignKey("GenreMajorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenreMajor");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiHistory", b =>
                {
                    b.HasOne("TumisugiApp.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.TumiManagement", "TumiManage")
                        .WithMany("Histories")
                        .HasForeignKey("TumiManageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("TumiManage");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiManagement", b =>
                {
                    b.HasOne("TumisugiApp.Models.Entities.GenreDetail", "GenreDetail")
                        .WithMany()
                        .HasForeignKey("GenreDetailCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.GenreMajor", "GenreMajor")
                        .WithMany()
                        .HasForeignKey("GenreMajorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenreDetail");

                    b.Navigation("GenreMajor");

                    b.Navigation("Platform");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreMajor", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiManagement", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
