// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TumisugiApp.Data;

#nullable disable

namespace TumisugiApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116125956_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreDetail", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreMajorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("GenreMajorCode");

                    b.ToTable("GetGenreDetails");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreMajor", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("GetGenreMajors");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.Platform", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.Status", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TumiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TumiManageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode");

                    b.HasIndex("TumiManageId");

                    b.ToTable("TumiHistories");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GanreDetailCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreDetailCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreMajorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreDetailCode");

                    b.HasIndex("GenreMajorCode");

                    b.HasIndex("PlatformCode");

                    b.HasIndex("StatusCode");

                    b.ToTable("TumiManagements");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreDetail", b =>
                {
                    b.HasOne("TumisugiApp.Models.Entities.GenreMajor", "GenreMajor")
                        .WithMany("Details")
                        .HasForeignKey("GenreMajorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenreMajor");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiHistory", b =>
                {
                    b.HasOne("TumisugiApp.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.TumiManagement", "TumiManage")
                        .WithMany("Histories")
                        .HasForeignKey("TumiManageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("TumiManage");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiManagement", b =>
                {
                    b.HasOne("TumisugiApp.Models.Entities.GenreDetail", "GenreDetail")
                        .WithMany()
                        .HasForeignKey("GenreDetailCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.GenreMajor", "GenreMajor")
                        .WithMany()
                        .HasForeignKey("GenreMajorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TumisugiApp.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenreDetail");

                    b.Navigation("GenreMajor");

                    b.Navigation("Platform");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.GenreMajor", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TumisugiApp.Models.Entities.TumiManagement", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
